### PR TITLE
Python bootstrap

### LINKED ISSUE #15: Use openZIM's bootstrap
Special attention points:
- CHANGELOG
- pin dependencies versions

### PR DESCRIPTION
**Pull request by benoit74**
## Rationale

Fix #15 

## Changes

- use `hatchling` for build (and `hatch` for development environment)
- backend package renamed `offspot_metrics_backend` for consistency
- many code fixes to pass ruff / pyright rules (or disable for some few lines)

- - -
This change is [Reviewable](https://reviewable.io/reviews/offspot/metrics/18)

### CODE REVIEW

**Comment by benoit74** [comment]
NOTA : codecov complains for files which have no tests at all ; tests are already ready and pending in the `frontend` branch as far as I remember + anyway we considered it was ok to not cover those files in previous PR

**Review by rgaudin — CHANGES_REQUESTED** [review]
Wow, such a large PR with so few things to say!

I see some files as renamed but some are deleted and added; Is this you or reviewable?

> Reviewed 39 of 66 files at r1, 25 of 27 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/offspot/metrics/18#-:-NaI7H3h1cPu1-XmbipZ:bk94o3d)* status: all files reviewed, 10 unresolved discussions (waiting on @benoit74)

___
*[`.github/workflows/PublishDockerDevImage.yaml` line 20 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHwF5u6ELmj4A1HzIj:-NaHwF5u6ELmj4A1HzIk:b90zbxa) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/.github/workflows/PublishDockerDevImage.yaml#L20)):*
> ```YAML
>           context: backend
>           image-name: offspot/metrics
>           tag-pattern: /^v([0-9.]+)$/
> ```

dev image should use `manual-tag`
___
*[`.github/workflows/Tests.yaml` line 51 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHwo_H6S4AiZPaFY2y:-NaHwo_H6S4AiZPaFY2z:bm3xaxn) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/.github/workflows/Tests.yaml#L51)):*
> ```YAML
>           docker run -d --rm --name test_container offspot_metrics_backend
>           sleep 5
>           docker ps | grep test_container
> ```

Although not required I'd stop the container ; helps catch stopping issues
___
*[`backend/CONTRIBUTING.md` line 18 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHx69o9ivD9C5d0wk9:-NaHx69o9ivD9C5d0wkA:b-d72upe) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/CONTRIBUTING.md#L18)):*
> ```Markdown
> 
> If not already installed on your machine, install it in your global environment:
> ```
> ```

Use a new line before comment blocks. GH is permissive but it's better to respect it for other readers
___
*[`backend/Dockerfile` line 23 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHy3MGD_7ru88cfySW:-NaHy3MGD_7ru88cfySX:bgz3pw3) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/Dockerfile#L23)):*
> ```Dockerfile
> RUN pip install --no-cache-dir /src \
>  && rm -rf /src
> ```

You should add an `EXPOSE` rule
___
*[`backend/Dockerfile` line 24 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHy9KzBRrPCjt5wDqX:-NaHy9L--voDp6LpCPIA:b-yi8v92) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/Dockerfile#L24)):*
> ```Dockerfile
>  && rm -rf /src
> 
> CMD ["uvicorn", "offspot_metrics_backend.entrypoint:app"]
> ```

Default is port `8000` no? Should probably specify `80`.
___
*[`backend/pyproject.toml` line 172 at r2](https://reviewable.io/reviews/offspot/metrics/18#-NaHXBPd60EwL9y4P_He:-NaHzGON1pawQBEINuN8:b-zcjvte) ([raw file](https://github.com/offspot/metrics/blob/6fc283348409404a1244e73d29da870d283a10b9/backend/pyproject.toml#L172)):*
<details><summary><i>Previously, benoit74 wrote…</i></summary><blockquote>

FYI
This is a difference compared to our bootstrap standard
</blockquote></details>

Thanks
___
*[`backend/README.md` line 0 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHzwe2AGT7PDaC2zNV:-NaHzwe2AGT7PDaC2zNW:bta1kgy) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/README.md#L0)):*
Maybe mention CONTRIBUTING?
___
*[`backend/tasks.py` line 1 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaI5tSx5PtRauhedJ6W:-NaI5tSx5PtRauhedJ6X:b-k4599j) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/tasks.py#L1)):*
> ```Python
> # pyright: strict, reportUntypedFunctionDecorator=false
> ```

What about `reportUnknownMemberType=false`?
___
*[`backend/tasks.py` line 22 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaI0qiDBo0qteAyIrE3:-NaI0qiDBo0qteAyIrE4:bx6m4tz) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/tasks.py#L22)):*
> ```Python
>     additional `args` supplied
>     """
>     environment_db_url = os.getenv("TEST_DATABASE_URL")
> ```

Can be simplified IMO. You don't need to conditionally do the alembic upgrade. It's harmless to run if already up to date.


```py
    test_db_path = None
    test_db_url = os.getenv("TEST_DATABASE_URL")
    if not test_db_url:
        temp_db_path = Path(
            NamedTemporaryFile(suffix=".db", prefix="test_", delete=False).name
        ).resolve()
        test_db_url = f"sqlite+pysqlite:////{temp_db_path}"

    try:
        ctx.run(
            f"{cmd} {args} ../tests{'/' + path if path else ''}",
            pty=use_pty,
            env={"DATABASE_URL": test_db_url},
        )
    finally:
        if test_db_path:
            test_db_path.unlink(missing_ok=True)
```
___
*[`backend/tasks.py` line 56 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaI3G7aEkcIo9xNV28u:-NaI3G7aEkcIo9xNV28v:b-fb0hhz) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/tasks.py#L56)):*
> ```Python
>     help={
>         "args": "pytest additional arguments",
>         "path": "path to test, relative to 'tests' parent folder",
> ```

Is this really useful? I prefer invoke tasks to be as transparent as possible from the underlying command (pytest here).
Unless this gets into the bootstrap, it's likely developers wont use it because it's not expected and would not look into it. People are already used to passing paths to pytest.
Or is it because of the `cd`?
___
*[`backend/tasks.py` line 117 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaI60qO7uKETQQA0lOK:-NaI60qO7uKETQQA0lOL:b-ftq7jr) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/tasks.py#L117)):*
> ```Python
>     """
>     ctx.run(
>         f"invoke alembic --cmd 'upgrade {rev}' {'--test-db' if test_db else ''}",
> ```

Don't call invoke from tasks. Call the method directly
___
*[`backend/src/offspot_metrics_backend/main.py` line 10 at r2](https://reviewable.io/reviews/offspot/metrics/18#-NaHZ42g7CfBt1FdGp9k:-NaI86RkBobtFMpC9hr5:b-mooudh) ([raw file](https://github.com/offspot/metrics/blob/6fc283348409404a1244e73d29da870d283a10b9/backend/src/offspot_metrics_backend/main.py#L10)):*
<details><summary><i>Previously, benoit74 wrote…</i></summary><blockquote>

FYI
Sourcing these values from pyproject.toml is complex + indeed we do not really want to absolutely have the same values since they serve different purpose (one is for the Python package, the other is for the OpenAPI documentation).
</blockquote></details>

I think both are good candidates for `__about__.py`

**Review by benoit74 — COMMENTED** [review]
Few things to say because it is almost the second time I'm doing the same thing. But also because I paid special attention to review my code myself before submitting the review. Glad you noticed the difference anyway ;o)

Regarding files that have been deleted and added, this is my fault. I renamed the folder manually and then `git add` the stuff, and git did not achieved to detect all moved files properly, I did not noticed it. I rewrote the commit and push forced. 

Note that I rewrote many things indeed, in order to have a clean git history and to test reviewable behavior in such situations (I don't like much to have "Fix following review" commits or stuff like that, this has nothing to do in the final git history).

> *[Reviewable](https://reviewable.io/reviews/offspot/metrics/18#-:-NaKdhsJ5CbUzX1KD9-J:b-dm7cpn)* status: 3 of 73 files reviewed, 10 unresolved discussions (waiting on @rgaudin)

___
*[`.github/workflows/PublishDockerDevImage.yaml` line 20 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHwF5u6ELmj4A1HzIj:-NaKefZ332bu79R4-D3S:byf7ixd) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/.github/workflows/PublishDockerDevImage.yaml#L20)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

dev image should use `manual-tag`
</blockquote></details>

Done.
I don't know why but I considered that `metrics` would be unreleased software, so I did not even included the `Publish` workflow.
I now think I'm wrong, it will be released, isn't it?
___
*[`.github/workflows/Tests.yaml` line 51 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHwo_H6S4AiZPaFY2y:-NaKj-hh-6gcd-X6Q3sk:b-896fix) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/.github/workflows/Tests.yaml#L51)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Although not required I'd stop the container ; helps catch stopping issues
</blockquote></details>

Done.
___
*[`backend/CONTRIBUTING.md` line 18 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHx69o9ivD9C5d0wk9:-NaKm_4_5Vp1kKttILlV:b-896fix) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/CONTRIBUTING.md#L18)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Use a new line before comment blocks. GH is permissive but it's better to respect it for other readers
</blockquote></details>

Done.
___
*[`backend/Dockerfile` line 23 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHy3MGD_7ru88cfySW:-NaKo6GK2cSsWH8WOsb8:b-896fix) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/Dockerfile#L23)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

You should add an `EXPOSE` rule
</blockquote></details>

Done.
___
*[`backend/Dockerfile` line 24 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHy9KzBRrPCjt5wDqX:-NaKo6lWDL74GlbOsdCQ:btsofa3) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/Dockerfile#L24)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Default is port `8000` no? Should probably specify `80`.
</blockquote></details>

Done
We also need to specify host so that it is binded to the external interface as well and not just localhost
___
*[`backend/README.md` line  at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHzwe2AGT7PDaC2zNV:-NaKoLZZ2r1JOj1Mhgib:b-896fix) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/README.md#L)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Maybe mention CONTRIBUTING?
</blockquote></details>

Done.
___
*[`backend/tasks.py` line 1 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaI5tSx5PtRauhedJ6W:-NaKoY56-H7J-OQFRoPe:b-896fix) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/tasks.py#L1)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

What about `reportUnknownMemberType=false`?
</blockquote></details>

Done.
___
*[`backend/tasks.py` line 22 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaI0qiDBo0qteAyIrE3:-NaKqfLy9gI8uJhEUBuQ:bb6un1j) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/tasks.py#L22)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Can be simplified IMO. You don't need to conditionally do the alembic upgrade. It's harmless to run if already up to date.


```py
    test_db_path = None
    test_db_url = os.getenv("TEST_DATABASE_URL")
    if not test_db_url:
        temp_db_path = Path(
            NamedTemporaryFile(suffix=".db", prefix="test_", delete=False).name
        ).resolve()
        test_db_url = f"sqlite+pysqlite:////{temp_db_path}"

    try:
        ctx.run(
            f"{cmd} {args} ../tests{'/' + path if path else ''}",
            pty=use_pty,
            env={"DATABASE_URL": test_db_url},
        )
    finally:
        if test_db_path:
            test_db_path.unlink(missing_ok=True)
```
</blockquote></details>

Done
___
*[`backend/tasks.py` line 56 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaI3G7aEkcIo9xNV28u:-NaKqkY_6FCdXJVgplGB:b-to1xz3) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/tasks.py#L56)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Is this really useful? I prefer invoke tasks to be as transparent as possible from the underlying command (pytest here).
Unless this gets into the bootstrap, it's likely developers wont use it because it's not expected and would not look into it. People are already used to passing paths to pytest.
Or is it because of the `cd`?
</blockquote></details>

it is because of the `cd` which was the only solution I got so that alembic achieves to find its configuration, but then forces to add '../tests/' as default path. 
Since you insisted on the oddity of the situation (and you are right :smile:), I finally found the solution in "initializer.py", just need to os.chdir (which is not very nice looking but way better than the other oddities I think).
___
*[`backend/tasks.py` line 117 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaI60qO7uKETQQA0lOK:-NaKwp3251FwaAmOaCQz:blj3f2w) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/tasks.py#L117)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Don't call invoke from tasks. Call the method directly
</blockquote></details>

Done.
Even if it is not (yet) possible to call a task from another task (see https://github.com/pyinvoke/invoke/issues/170), I had to isolate the shared code in a method, but this is OK.
___
*[`backend/src/offspot_metrics_backend/main.py` line 10 at r2](https://reviewable.io/reviews/offspot/metrics/18#-NaHZ42g7CfBt1FdGp9k:-NaLQmgK5rHHZF27yqsh:b-qf639p) ([raw file](https://github.com/offspot/metrics/blob/6fc283348409404a1244e73d29da870d283a10b9/backend/src/offspot_metrics_backend/main.py#L10)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

I think both are good candidates for `__about__.py`
</blockquote></details>

Done
Are you aware of anything which could be used to source dynamically information in `__about__.py` for use in `pyproject.toml`? Because in this same `main.py` we repeat information regarding authors, license, ...

**Review by benoit74 — COMMENTED** [review]
Note : git did not achieved to totally move the files correctly, there are still some files which are marked as deleted and added again, I don't know why ...

> *[Reviewable](https://reviewable.io/reviews/offspot/metrics/18#-:-NaLd8ZMATTfJ4rnShJB:b2doq4k)* status: 3 of 73 files reviewed, 10 unresolved discussions (waiting on @rgaudin)

**Review by benoit74 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/offspot/metrics/18)* status: 3 of 73 files reviewed, 12 unresolved discussions (waiting on @rgaudin)

___
*[`.github/workflows/Publish.yaml` line 28 at r5](https://reviewable.io/reviews/offspot/metrics/18#-NaLem4f6Ng6BW2Ua81d:-NaLem4g2Ch3ZyY1NduD:bgtiq3i) ([raw file](https://github.com/offspot/metrics/blob/813e709accce6b2934e0337942d925c4b227a33d/.github/workflows/Publish.yaml#L28)):*
> ```YAML
>           python -m build --sdist --wheel
> 
>       - name: Upload to PyPI
> ```

Do we want to publish to PyPi ?
___
*[`.github/workflows/Publish.yaml` line 37 at r5](https://reviewable.io/reviews/offspot/metrics/18#-NaLewl8-8wdXcDGjz2r:-NaLewl8-8wdXcDGjz2s:b52bx6) ([raw file](https://github.com/offspot/metrics/blob/813e709accce6b2934e0337942d925c4b227a33d/.github/workflows/Publish.yaml#L37)):*
> ```YAML
>         with:
>           context: backend
>           image-name: offspot/metrics_backend
> ```

I renamed the image since there will also be a frontend image I imagine (at least).

**Review by rgaudin — CHANGES_REQUESTED** [review]
It's good that it's verbose in expose all the renames but it had me individually accept every files, even if there was no change inside

> Reviewed 70 of 70 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/offspot/metrics/18#-:-NaM9AAcB2BeSXnpN6H1:b-m5yd33)* status: all files reviewed, 6 unresolved discussions (waiting on @benoit74)

___
*[`.github/workflows/Publish.yaml` line 28 at r5](https://reviewable.io/reviews/offspot/metrics/18#-NaLem4f6Ng6BW2Ua81d:-NaLlwTV7n4LyfYIADWY:b32w12) ([raw file](https://github.com/offspot/metrics/blob/813e709accce6b2934e0337942d925c4b227a33d/.github/workflows/Publish.yaml#L28)):*
<details><summary><i>Previously, benoit74 wrote…</i></summary><blockquote>

Do we want to publish to PyPi ?
</blockquote></details>

No
___
*[`.github/workflows/Publish.yaml` line 37 at r5](https://reviewable.io/reviews/offspot/metrics/18#-NaLewl8-8wdXcDGjz2r:-NaLm-er44yZVkgcguiq:b-ulcfqc) ([raw file](https://github.com/offspot/metrics/blob/813e709accce6b2934e0337942d925c4b227a33d/.github/workflows/Publish.yaml#L37)):*
<details><summary><i>Previously, benoit74 wrote…</i></summary><blockquote>

I renamed the image since there will also be a frontend image I imagine (at least).
</blockquote></details>

Good call
___
*[`.github/workflows/PublishDockerDevImage.yaml` line 20 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHwF5u6ELmj4A1HzIj:-NaLuOnd71HquH_6KCTj:b-nnvhj9) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/.github/workflows/PublishDockerDevImage.yaml#L20)):*
<details><summary><i>Previously, benoit74 wrote…</i></summary><blockquote>

Done.
I don't know why but I considered that `metrics` would be unreleased software, so I did not even included the `Publish` workflow.
I now think I'm wrong, it will be released, isn't it?
</blockquote></details>

It will be released. Actually it will need to be published for arm64 as well and it's an alpine candidate. But that can be in a separate issue
___
*[`.github/workflows/PublishDockerDevImage.yaml` line 21 at r5](https://reviewable.io/reviews/offspot/metrics/18#-NaLuf2s7CfZF45JlnyU:-NaLuf2s7CfZF45JlnyV:bb7phvt) ([raw file](https://github.com/offspot/metrics/blob/813e709accce6b2934e0337942d925c4b227a33d/.github/workflows/PublishDockerDevImage.yaml#L21)):*
> ```YAML
>           image-name: offspot/metrics_backend
>           manual-tag: dev
>           atest-on-tag: false
> ```

typo
___
*[`backend/tasks.py` line 117 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaI60qO7uKETQQA0lOK:-NaLy_dU-EkjSlfVBP7N:b-kps7o0) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/backend/tasks.py#L117)):*
<details><summary><i>Previously, benoit74 wrote…</i></summary><blockquote>

Done.
Even if it is not (yet) possible to call a task from another task (see https://github.com/pyinvoke/invoke/issues/170), I had to isolate the shared code in a method, but this is OK.
</blockquote></details>

Yes, sorry that's what I meant
___
*[`backend/src/offspot_metrics_backend/main.py` line 10 at r2](https://reviewable.io/reviews/offspot/metrics/18#-NaHZ42g7CfBt1FdGp9k:-NaM2hsWEVq0B-pZ2i5V:b-u0mb5i) ([raw file](https://github.com/offspot/metrics/blob/6fc283348409404a1244e73d29da870d283a10b9/backend/src/offspot_metrics_backend/main.py#L10)):*
<details><summary><i>Previously, benoit74 wrote…</i></summary><blockquote>

Done
Are you aware of anything which could be used to source dynamically information in `__about__.py` for use in `pyproject.toml`? Because in this same `main.py` we repeat information regarding authors, license, ...
</blockquote></details>

AFAIK only dynamic version is supported out of the box but you can use a hook.
See https://github.com/pypa/hatch/issues/373 and https://github.com/hynek/hatch-fancy-pypi-readme
The other way is to query the installed package metadata but it's limited and fragile

Naive test
```py
import pkg_resources
import offspot_metrics_backend
dist = pkg_resources.get_distribution(offspot_metrics_backend.__package__)
list(dist.get_metadata_lines(dist.PKG_INFO))
```
___
*[`backend/src/offspot_metrics_backend/db/initializer.py` line 12 at r5](https://reviewable.io/reviews/offspot/metrics/18#-NaM8Yu02qp5zeBpP6yb:-NaM8Yu1-0tMk0ATSMVV:b-noyict) ([raw file](https://github.com/offspot/metrics/blob/813e709accce6b2934e0337942d925c4b227a33d/backend/src/offspot_metrics_backend/db/initializer.py#L12)):*
> ```Python
> class Initializer:
>     @staticmethod
>     def ensure_schema_is_up_to_date(src_dir: str | None = None):
> ```

Can we use pathlib? Just so there's no place in code where we manipulate paths as string.

**Review by benoit74 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/offspot/metrics/18)* status: all files reviewed, 3 unresolved discussions (waiting on @rgaudin)

___
*[`.github/workflows/PublishDockerDevImage.yaml` line 20 at r3](https://reviewable.io/reviews/offspot/metrics/18#-NaHwF5u6ELmj4A1HzIj:-NaMF4Or9ZpGYzcOuxQ-:b-896fix) ([raw file](https://github.com/offspot/metrics/blob/56f6eda54aa92c779e7999b7c27150652d1ac6b5/.github/workflows/PublishDockerDevImage.yaml#L20)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

It will be released. Actually it will need to be published for arm64 as well and it's an alpine candidate. But that can be in a separate issue
</blockquote></details>

Done.
___
*[`backend/src/offspot_metrics_backend/db/initializer.py` line 12 at r5](https://reviewable.io/reviews/offspot/metrics/18#-NaM8Yu02qp5zeBpP6yb:-NaMFZhE5_Bck0hvqACR:b-896fix) ([raw file](https://github.com/offspot/metrics/blob/813e709accce6b2934e0337942d925c4b227a33d/backend/src/offspot_metrics_backend/db/initializer.py#L12)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Can we use pathlib? Just so there's no place in code where we manipulate paths as string.
</blockquote></details>

Done.

**Review by rgaudin — APPROVED** [review]
> Reviewed 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/offspot/metrics/18)* status: 72 of 73 files reviewed, all discussions resolved (waiting on @benoit74)

**Pull request merged**
